# Generated by Django 4.1.6 on 2023-02-14 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0002_tipomenu'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tipomenu',
            options={'ordering': ['-created'], 'verbose_name': 'tipo de menu', 'verbose_name_plural': 'tipos de menú'},
        ),
        migrations.AddField(
            model_name='menu',
            name='tipoMenu',
            field=models.ManyToManyField(blank=True, null=True, to='menu.tipomenu', verbose_name='Tipo de menú'),
        ),
    ]
