# Generated by Django 4.1.6 on 2023-02-14 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0003_alter_tipomenu_options_menu_tipomenu'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='reviews',
            field=models.SmallIntegerField(verbose_name='Número de reseñas'),
        ),
    ]
